### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by rmohashi**
## Objective
* Text improvements and typo fixes

## Checklist

- [x] I have read the **[CONTRIBUTING]** document.
- [x] I have updated the documentation accordingly.

[CONTRIBUTING]: https://github.com/codus/codelog/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by emilianoLeite** [comment]
@rmohashi I have no idea whats happening with Travis. I tried restarting the jobs, but the errors continue

**Comment by rmohashi** [comment]
@emilianoLeite I see. We can wait and try again or just ignore it. What do you think?

**Comment by emilianoLeite** [comment]
@rmohashi Its your call. But I think it would be better if we investigate and resolve this issue, so any new PR is not affected by it.

**Comment by rmohashi** [comment]
@emilianoLeite It's working now! For some reason(probably because I accidentally pushed my branch to the original repository first), Travis is trying to clone the branch from `codus` repository, but it only exists on my fork.

**Comment by emilianoLeite** [comment]
@rmohashi The `travis-ci/push` is still failing, perhaps for the same reason?

**Comment by emilianoLeite** [comment]
If its a branch problem you can just go ahead and merge this PR

**Pull request merged**
